[project]
name = "gitraze"
version = "0.2.5"
description = "A CLI and Python library for GitHub reconnaissance, search, and analysis"
authors = [{ name = "AK Pandey" }]
dependencies = ["requests", "colorama"]
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"

keywords = ["github", "cli", "api", "recon", "search", "github-user", "repository"]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

[project.scripts]
gitraze = "gitraze.cli:main"

[project.urls]
Homepage = "https://github.com/akpandey-dev/gitraze"

[build-system]
requires = ["setuptools>=77.0.0"]
build-backend = "setuptools.build_meta"